### ISSUE TITLE
Any thoughts on CGGTTS validation?

### ISSUE THREAD

**Issue by aidanmontare-fed** [gwbres/cggtts#14]
Hi! This is kind of a general question, but have you thought about use cases that are more along the lines of validating CGGTTS files?

I'm working on a web application for common view time transfer, and I was considering using CGGTTS as input from clients, but I'm trying to think of ways to validate the input, both from a data cleaning perspective and also from a security perspective.

Just curious if you've thought about things like this or have any ideas!

(And, if you'd like something like this in the library, I've been meaning to learn Rust for a while, so I might be interested in giving it a go.)

**Comment by gwbres** [comment]
Hello @aidanmontare-fed,

Right now `rinex-cli` is our main application, it is capable of generating CGGTTS solutions (by combing this crate to gnss-rtk and RINEX) and is also capable of reporting the solutions, so it allows quality verification (in that sense). [Check this out for example](https://github.com/georust/rinex/blob/main/tutorials/GAL/mojdnk-brdc.sh). 

![map](https://github.com/user-attachments/assets/73d82b2e-b748-45bf-beb7-8ec2444d0876)
![refsys](https://github.com/user-attachments/assets/f0a51a1d-ee62-4fe0-8373-02ecf8c5f3b1)

But it does not accept CGGTTS input files at the moment, therefore, does not permit common view comparison

Obviously, quality of the data depends on the clocks quality and the applications itself, so there's not much you can do other than rendering the data as is. You can add markers and report extreme values.

Only if you know the clock profile and the targetted application, _then_ you can add tolerated ranges that it should not exceed. For example, in GNSS-RTK we do not allow SV with troposphere bias > 100m and propagation delay > 200ms, because those are physical non sense that are totally uncorrelated from the local clock quality, the navigation applications or the user profile.

CGGTTS is somewhat dedicated to high precision, so reference frames that are not precise (unlike ITRF) look suspicious or said to be forbidden.

Also, only high quality / profesisonal delay calibrations will permit very precise common view comparison. Without proper delay calibration of the setup, the transfer will be limited by this lack of accuracy. CGGTTS allows complete delay specs, but therefore can be complex. It is not even fully documented. I once held a piece of paper that explained the delay specs, but I can't seem to find it right now. I will try to find it and will reach out on this very topic. Also, if you can contact me by email, I can send you the official "CGGTTS guidelines", that come with the CGGTTS specs but are unfortunately not posted along the specs.

As far as "security" goes, CGGTTS files come with a checksum as you probably know already, so checksum verification is pretty much all you can do ? if you had a database of official producers, you could imagine accepting solutions from those agencies only, but I'm not sure this is of any help.

**Comment by gwbres** [comment]
How to accurately describe Delay specs for a given setup :

![image](https://github.com/user-attachments/assets/d1c01583-c9f1-40e1-be70-afe9b85cfe02)
